# GitHub Actions workflow template for Sentry MCP Analytics
# Copy to .github/workflows/test-mcp-analytics.yml

name: Test Sentry MCP Analytics

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-mcp-analytics:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Verify Sentry patches applied
      run: npm run verify-patches

    - name: Test MCP analytics setup
      run: npm run test-mcp-analytics

    - name: Build project
      run: npm run build

    - name: Run linting
      run: npm run lint

    - name: Report success
      if: success()
      run: |
        echo "✅ MCP Analytics setup verified successfully"
        echo "🎯 Production deployment ready with full Sentry MCP tracking"