import express from 'express';
import { streamText } from 'ai';
import { databaseService } from '../db/database-service.js';
import { StatusStreamer, wrapToolsWithStatus } from '../utils/status-streaming.js';
import * as Sentry from '@sentry/node';
import { AIProviderService, type AIProvider } from '../services/ai-provider.js';

const { logger } = Sentry;

const PRIORITY_LOW = 'low';
const PRIORITY_MEDIUM = 'medium';
const PRIORITY_HIGH = 'high';
const VALID_PRIORITIES = new Set<string>([PRIORITY_LOW, PRIORITY_MEDIUM, PRIORITY_HIGH]);

interface MVPTaskPayload {
  title: string;
  description?: string;
  priority?: string;
}

interface MVPTechStackPayload {
  frontend?: string;
  backend?: string;
  database?: string;
  hosting?: string;
}

interface MVPPlanPayload {
  projectName: string;
  description?: string;
  features?: string[];
  techStack?: MVPTechStackPayload;
  tasks: MVPTaskPayload[];
}

function normalizePriority(priority?: string): 'low' | 'medium' | 'high' {
  if (!priority || typeof priority !== 'string') {
    return PRIORITY_MEDIUM;
  }

  const normalized = priority.toLowerCase().trim();
  if (VALID_PRIORITIES.has(normalized)) {
    return normalized as 'low' | 'medium' | 'high';
  }

  if (normalized.includes('high')) {
    return PRIORITY_HIGH;
  }
  if (normalized.includes('low')) {
    return PRIORITY_LOW;
  }
  return PRIORITY_MEDIUM;
}

function buildProjectDescription(plan: MVPPlanPayload): string {
  const sections: string[] = [];

  if (plan.description) {
    sections.push(plan.description.trim());
  }

  const techStackParts: string[] = [];
  if (plan.techStack?.frontend) techStackParts.push(`Frontend: ${plan.techStack.frontend}`);
  if (plan.techStack?.backend) techStackParts.push(`Backend: ${plan.techStack.backend}`);
  if (plan.techStack?.database) techStackParts.push(`Database: ${plan.techStack.database}`);
  if (plan.techStack?.hosting) techStackParts.push(`Hosting: ${plan.techStack.hosting}`);

  if (techStackParts.length) {
    sections.push(`Tech Stack:\n- ${techStackParts.join('\n- ')}`);
  }

  if (Array.isArray(plan.features) && plan.features.length > 0) {
    const featureList = plan.features.map((feature) => `- ${feature}`).join('\n');
  sections.push(`Core Features:\n${featureList}`);
  }

  if (Array.isArray(plan.tasks) && plan.tasks.length > 0) {
    const previewTasks = plan.tasks.slice(0, 5).map((task: MVPTaskPayload, index: number) => {
      const priority = normalizePriority(task.priority);
      return `${index + 1}. ${task.title} (${priority}) - ${task.description || 'No description provided'}`;
    }).join('\n');
    sections.push(`Initial Tasks Preview:\n${previewTasks}${plan.tasks.length > 5 ? '\n...and more tasks generated by the MVP builder.' : ''}`);
  }

  return sections.join('\n\n');
}

export const aiRoutes = express.Router();

aiRoutes.post('/generate-details', async (req: any, res: any) => {
  // Declare variables at function scope so they're accessible in catch blocks
  let userId: string | undefined;
  
  try {
    const { prompt, context } = req.body;
    
    if (!prompt) {
      return res.status(400).json({ error: 'Prompt is required' });
    }

    // Get authenticated user ID
    userId = req.user?.id;
    if (!userId) {
      return res.status(401).json({ error: 'User not authenticated' });
    }

    // Get the appropriate AI model
    let model;
    try {
      model = await AIProviderService.getModel(userId);
    } catch (error) {
      return res.status(500).json({ 
        error: error instanceof Error ? error.message : 'Failed to get AI model' 
      });
    }

    const systemPrompt = `You are a senior technical lead helping to generate detailed implementation plans and build processes for development tasks.

Context:
- Task Title: ${context?.title || 'Not provided'}
- Task Description: ${context?.description || 'Not provided'}
- Task Priority: ${context?.priority || 'Not provided'}

Generate a comprehensive build process and implementation details for this task. Focus on creating an actionable step-by-step implementation guide that a developer can follow. Your response should include:

## Implementation Details
- Step-by-step build process
- Technical approach and architecture decisions
- Code structure and file organization
- Key components/modules needed

## Acceptance Criteria
- Clear definition of "done" for this task
- Testable requirements
- Expected functionality and behavior

## Technical Requirements
- Dependencies and libraries needed
- Configuration requirements
- Environment setup needs
- Database schema changes (if applicable)

Format your response in markdown with clear sections and actionable steps. Be specific about implementation details while keeping it practical and achievable.`;

    // Set headers for streaming
    res.setHeader('Content-Type', 'text/plain; charset=utf-8');
    res.setHeader('Transfer-Encoding', 'chunked');
    res.setHeader('Cache-Control', 'no-cache');
    res.setHeader('Connection', 'keep-alive');

    const result = streamText({
      model,
      experimental_telemetry: {
        isEnabled: true,
        functionId: "generate-details"
      },
      system: systemPrompt,
      onError: (error) => {
        console.error('AI generation error:', error);
      },
      prompt: prompt,
      // Removed maxTokens - not supported by responses API
    });

    // Stream the text chunks to the client
    for await (const chunk of result.textStream) {
      res.write(chunk);
    }

    res.end();
  } catch (error) {
    console.error('AI generation error:', error);
    if (!res.headersSent) {
      res.status(500).json({ error: 'Failed to generate details' });
    } else {
      res.end();
    }
  }
});


aiRoutes.post('/generatemvp', async (req: any, res: any) => {
  try {
    const { projectIdea, selectedComponents } = req.body;
    
    if (!projectIdea) {
      return res.status(400).json({ error: 'Project idea is required' });
    }

    // Get authenticated user ID
    const userId = req.user?.id;
    if (!userId) {
      return res.status(401).json({ error: 'User not authenticated' });
    }

    // Get the appropriate AI model for MVP generation
    let model;
    try {
      const config = await AIProviderService.getMVPGenerationModel(userId);
      model = config.model;
    } catch (error) {
      return res.status(500).json({ 
        error: error instanceof Error ? error.message : 'Failed to get AI model' 
      });
    }

    const systemPrompt = `You are an expert product manager and technical architect who helps create detailed MVP (Minimum Viable Product) plans for software projects.

Based on the user's project idea, create a comprehensive MVP plan that includes:

1. A clear project name and description
2. Core features that are essential for the MVP (keep it minimal but functional)
3. Recommended tech stack (frontend, backend, database, hosting)
4. Detailed development tasks broken down into actionable items that would enable the MVP to be built and launched quickly while still providing the core functionality. 

Focus on creating an MVP that can be built and launched quickly while still providing value to users. Prioritize essential features only.

Task descriptions should be in the format of prompts that an AI can use to generate code for that specific task. It should be a detailed description of the task, written from the perspective of a senior developer focused on that task space.

For UI related tasks, prefer to use Shadcn UI and Tailwind CSS as part of the build.

For database related tasks, prefer to use PostgreSQL and use Drizzle ORM to manage it. Include these in the tasks.

${selectedComponents && selectedComponents.length > 0 ? `
SELECTED COMPONENTS:
The user has selected the following reusable components to incorporate into their MVP:

${selectedComponents.map((comp: any, index: number) => `
${index + 1}. ${comp.name}
   Description: ${comp.description}
   Tags: ${comp.tags?.join(', ') || 'None'}
`).join('')}

Please incorporate the guidance and patterns from these selected components when creating the tech stack recommendations and development tasks. Use the component descriptions to inform your approach to the project architecture and implementation strategy.
` : ''}

Respond with a JSON object in this exact format:
{
  "projectName": "Clear, concise project name",
  "description": "Brief description of what the MVP does",
  "features": [
    "List of core features needed for MVP",
    "Each feature should be essential and user-facing"
  ],
  "techStack": {
    "frontend": "Recommended frontend technology/framework",
    "backend": "Recommended backend technology/framework", 
    "database": "Recommended database solution",
    "hosting": "Optional hosting recommendation"
  },
  "tasks": [
    {
      "title": "Task title",
      "description": "Detailed description of what needs to be done",
      "priority": "high|medium|low"
    }
  ]
}

CRITICAL: Your response must be ONLY the JSON object, with no markdown formatting, no code blocks, no additional text before or after. Start directly with { and end with }.`;

    // Set headers for streaming
    res.setHeader('Content-Type', 'text/plain; charset=utf-8');
    res.setHeader('Transfer-Encoding', 'chunked');
    res.setHeader('Cache-Control', 'no-cache');
    res.setHeader('Connection', 'keep-alive');

    // Get provider options for o3 reasoning summaries
    const user = await databaseService.getUserById(userId);
    const provider = user?.aiProvider || 'anthropic';
    const providerOptions = AIProviderService.getProviderOptions(provider);
    
    const result = streamText({
      model,
      experimental_telemetry: {
        isEnabled: true,
        functionId: "mvp-plan-generation"
      },
      system: systemPrompt,
      prompt: `Create an MVP plan for: ${projectIdea}`,
      // Add provider options for reasoning summaries
      ...(Object.keys(providerOptions).length > 0 && { providerOptions })
    });

    // Stream the text chunks to the client
    for await (const chunk of result.textStream) {
      res.write(chunk);
    }
    res.end();
  } catch (error) {
    console.error('MVP generation error:', error);
    if (!res.headersSent) {
      res.status(500).json({ error: 'Failed to generate MVP plan' });
    } else {
      res.end();
    }
  }
});


aiRoutes.post('/create-mvp-project', async (req: any, res: any) => {
  let userId: string | undefined;
  let userProvider: AIProvider = 'anthropic';
  let statusStreamer: StatusStreamer | null = null;
  let mvpPlan: MVPPlanPayload;

  try {
    const rawPlan = req.body.mvpPlan as MVPPlanPayload | undefined;
    if (!rawPlan) {
      return res.status(400).json({ error: 'MVP plan is required' });
    }

    if (!Array.isArray(rawPlan.tasks) || rawPlan.tasks.length === 0) {
      return res.status(400).json({ error: 'MVP plan must include at least one task' });
    }

    mvpPlan = {
      ...rawPlan,
      tasks: rawPlan.tasks
    };

    userId = req.user?.id;
    if (!userId) {
      return res.status(401).json({ error: 'User not authenticated' });
    }

    const user = await databaseService.getUserById(userId);
    userProvider = user?.aiProvider === 'openai' ? 'openai' : 'anthropic';

    console.log(`

🎆 [35m[MVP_CREATE][0m Starting MVP creation
   📝 Project: [33m${mvpPlan.projectName}[0m
   🗺️ Tasks: [36m${mvpPlan.tasks.length}[0m
   ⚙️ Execution: [32mDeterministic server flow[0m
`);
    logger.info('Starting MVP creation (deterministic flow)', {
      userId,
      provider: userProvider,
      projectName: mvpPlan.projectName,
      taskCount: mvpPlan.tasks.length
    });

    res.setHeader('Content-Type', 'text/plain; charset=utf-8');
    res.setHeader('Transfer-Encoding', 'chunked');
    res.setHeader('Cache-Control', 'no-cache');
    res.setHeader('Connection', 'keep-alive');

    statusStreamer = StatusStreamer.createWrapper(res, {
      userId,
      provider: userProvider || 'unknown',
      operation: 'create_mvp_project',
      projectName: mvpPlan.projectName,
      taskCount: mvpPlan.tasks.length
    }, false);

    statusStreamer.sendProgressUpdate(`🚀 Starting MVP creation for "${mvpPlan.projectName}" with ${mvpPlan.tasks.length} tasks`);

    const { createTaskTools } = await import('../tools/task-tools.js');
    const taskTools = createTaskTools(userId);
    const wrappedTools = wrapToolsWithStatus({
      createProject: taskTools.createProject,
      createTask: taskTools.createTask
    }, statusStreamer);

    (globalThis as any).mvpTaskCount = mvpPlan.tasks.length;

    const projectDescription = buildProjectDescription(mvpPlan);
    const projectResult = await wrappedTools.createProject.execute({
      name: mvpPlan.projectName,
      description: projectDescription
    });

    if (!projectResult?.success || !projectResult.data?.id) {
      throw new Error(projectResult?.message || 'Failed to create project');
    }

    const projectId = projectResult.data.id;
    let createdTasks = 0;

    for (const task of mvpPlan.tasks) {
      const taskResult = await wrappedTools.createTask.execute({
        projectId,
        title: task.title,
        description: task.description,
        priority: normalizePriority(task.priority)
      });

      if (taskResult?.success === false) {
        throw new Error(taskResult?.message || `Failed to create task "${task?.title || 'unknown'}"`);
      }

      createdTasks += 1;
      statusStreamer.sendProgressUpdate(`Progress: ${createdTasks}/${mvpPlan.tasks.length} tasks created`);
    }

    statusStreamer.sendCompletion(`🎉 MVP "${mvpPlan.projectName}" created successfully with ${mvpPlan.tasks.length} tasks!`);
    console.log(`
✨ [32m[MVP_CREATE][0m Completed deterministic flow for project: [33m${mvpPlan.projectName}[0m
${'='.repeat(60)}
`);
    logger.info('MVP creation completed (deterministic flow)', {
      userId,
      provider: userProvider,
      projectId,
      projectName: mvpPlan.projectName,
      taskCount: mvpPlan.tasks.length
    });
  } catch (error) {
    console.error(`
🚨 [31m[MVP_CREATE][0m Error during MVP creation:`, error);
    logger.error('MVP creation failed (deterministic flow)', {
      userId: userId || 'unknown',
      provider: userProvider,
      projectName: mvpPlan?.projectName,
      taskCount: mvpPlan?.tasks?.length,
      error: error instanceof Error ? error.message : 'Unknown error'
    });

    if (statusStreamer) {
      const errorMessage = error instanceof Error ? error.message : 'Failed to create MVP project.';
      statusStreamer.sendStatus({
        type: 'tool-error',
        status: 'error',
        message: `❌ MVP creation failed: ${errorMessage}`,
        data: { error: errorMessage }
      });
    } else if (!res.headersSent) {
      res.status(500).json({ error: 'Failed to create MVP project' });
    }
  } finally {
    statusStreamer?.close();
  }
});
